# 站点设置
title: "你的网站名称"
name: "你的名字"
description: "网站描述"

# 主题设置
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default" # 可选 default, air, dark, dusk, neon

# 插件
plugins:
  - jekyll-include-cache

# 构建设置
markdown: kramdown
permalink: /:categories/:title/

# 作者信息
author:
  name: "你的名字"
  bio: "个人简介"
  location: "位置"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Yanze66"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-github"
      url: "https://scholar.google.com/citations?view_op=list_works&hl=en&user=D7uiX0AAAAAJ&gmla=AKzYXQ2pEES98hFLTZ0Bu5VchQ1AjE6TVDnzYV3Z3EVHIxNSm4xE1CnqbYc36w1jUCoE1ojZYOd82Qw54LLI3svjzZrXDmvzSg"

# 默认设置
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
