# 站点设置
title: "Yanze's Homepage"
name: "吴彦泽"
description: "闲暇之余创建的网站"

# 主题设置
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default" # 可选 default, air, dark, dusk, neon

# 插件
plugins:
  - jekyll-include-cache

# 构建设置
markdown: kramdown
permalink: /:categories/:title/

# 作者信息
author:
  name: "Yanze Wu"
  bio: "Pursuing IT PhD at George Mason University. 2024 - current  "
  location: "Fairfax, VA, US"
  mail: "ywu42@gmu.edu"
  phone: "+1 571-604-4865"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Yanze66"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google-scholar"
      url: "https://scholar.google.com/citations?view_op=list_works&hl=en&user=D7uiX0AAAAAJ&gmla=AKzYXQ2pEES98hFLTZ0Bu5VchQ1AjE6TVDnzYV3Z3EVHIxNSm4xE1CnqbYc36w1jUCoE1ojZYOd82Qw54LLI3svjzZrXDmvzSg"
    - label: "resume"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/files/resume.pdf"
# 默认设置
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
